### ISSUE TITLE
Problem with expired transaction IDs when rolling back transactions

### ISSUE THREAD

**Issue by jordan-dimov** [chanzuckerberg/aurora-data-api#31]
I was getting Boto errors in the logs of my Lambda's about expired transaction IDs when `aurora_data_api` tries to rollback a transaction. 

AWS docs say that: "If the transaction ID has expired, the transaction was rolled back automatically. In this case, an aws rds-data rollback-transaction command that specifies the expired transaction ID returns an error."

So I tried catching that exception and ignoring it in aurora_data_api ... because presumably the transaction has already been rolled back automatically. I did this by adding a try/except around the `rollback_transaction()` call here: https://github.com/cloud-utils/aurora-data-api/blob/509cefe2645af0d9cc21449fb739a18b13410062/aurora_data_api/__init__.py#L63 

    try:
        self._client.rollback_transaction(
            resourceArn=self._aurora_cluster_arn,
            secretArn=self._secret_arn,
            transactionId=self._transaction_id,
        )
    except (BotoCoreError, ClientError) as exception:
        logger.warning(
            "Transaction ID has expired - ignoring rollback request. ",
            extra={
                "transaction_id": self._transaction_id,
                "exception": str(exception),
            },
        )

And then in `execute()`, I had to add another `elif` after this one: https://github.com/cloud-utils/aurora-data-api/blob/509cefe2645af0d9cc21449fb739a18b13410062/aurora_data_api/__init__.py#L227 

    elif re.search(r"Transaction \S+ is not found", str(e)) or (
        "Invalid transaction ID" in str(e)
    ):
        self._transaction_id = None
        self.execute(operation, parameters=parameters)

This seems to work, and I no longer get those errors, but I'm not at all sure it's a good (or even correct) solution. Or what the actual root of the problem is. I still get those warning logs I've added (`Transaction ID has expired...`) several times a day.

**Comment by jordan-dimov** [comment]
To clarify, this happens while accessing PostgreSQL on Aurora via the Data Api, and my application code is actually using `sqlalchemy-aurora-data-api` (which relies on `aurora-data-api` internally). 

The transaction ID expiration could very well be a configuration issue, but I'm not sure what config that would be.

**Comment by jordan-dimov** [comment]
Further clarification: the original errors I was getting (before my "fixes") looked like this: 

`botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the RollbackTransaction operation: Transaction AVCZtc6DH/GfPuWCv+79t+kSYtkvhLrsGt9kjLA+TcLr6soPiSf5CAdYiG2HPTcKtcxNPZD1JTBTY47F5cooVtGmtobCNEDnAcLtVbhXxGZPAITaHngWUIYyEZMFeRT8v/8KtR6YCZcGptYTywr8N+/6PdqrQchzIY8v773nYnBbmZrQyY55xJYxCYWZ3c9/2bepBOiIqIAm is not found`

Here's the full traceback: 

```
Traceback (most recent call last):
  File "/var/task/sqlalchemy/pool/base.py", line 682, in _finalize_fairy
    fairy._reset(pool)
  File "/var/task/sqlalchemy/pool/base.py", line 887, in _reset
    pool._dialect.do_rollback(self)
  File "/var/task/sqlalchemy/engine/default.py", line 667, in do_rollback
    dbapi_connection.rollback()
  File "/var/task/aurora_data_api/__init__.py", line 63, in rollback
    self._client.rollback_transaction(resourceArn=self._aurora_cluster_arn,
  File "/var/task/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
```
